[package]
name = "fox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.9.4"
clap = { version = "3.2.12", features = ["derive"] }
tokio = { version = "1.20.0", features = ["full"] }
